### ISSUE TITLE
This project does not work when building.

### ISSUE THREAD

**Issue by rossanodr** [bracesproul/gen-ui#10]
This repo works nicely with yarn run dev,
but it gets errors like [EmptyChannelError] when I try to run it after building or when I try to deploy it on Vercel.

**Comment by rossanodr** [comment]
fixed:
original code: `  const graph = workflow.compile();`
fix: `  const graph = workflow.compile({});`

**Comment by rossanodr** [comment]
EmptyChannelError appeared again

**Comment by bracesproul** [comment]
This should be fixed by #12!
