### ISSUE TITLE
Vercel Support

### ISSUE THREAD

**Issue by evanlong-me** [bracesproul/gen-ui#15]
Hopefully it will support Vercel, like [lobe-chat](https://github.com/lobehub/lobe-chat) 😊

**Comment by bracesproul** [comment]
Can you expand on what you mean by "Vercel support"? @evanlong0803

**Comment by evanlong-me** [comment]
Vercel One-Click Deployment

**Comment by bracesproul** [comment]
Just added a badge in this PR! https://github.com/bracesproul/gen-ui/pull/18
